const DB_NAME='english-flow-secure', STORE='chat-devices', VERSION=2;
const te=new TextEncoder(), td=new TextDecoder();
function b64(buf){return btoa(String.fromCharCode(...new Uint8Array(buf))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function fromB64(s){const x=String(s||'').replace(/-/g,'+').replace(/_/g,'/');const pad='='.repeat((4-x.length%4)%4);const bin=atob(x+pad);return Uint8Array.from(bin,c=>c.charCodeAt(0))}
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'deviceId'});if(db.objectStoreNames.contains('chat-keys')){const old=r.transaction.objectStore('chat-keys');const req=old.get('identity');req.onsuccess=()=>{if(req.result?.privateJwk&&req.result?.publicJwk){db.transaction(STORE,'readwrite').objectStore(STORE).put({deviceId:localDeviceId(),...req.result,keyVersion:1})}}}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function localDeviceId(){let id=localStorage.getItem('ef-chat-device');if(!id){id=crypto.randomUUID();localStorage.setItem('ef-chat-device',id)}return id}
async function getDevice(id=localDeviceId()){const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readonly').objectStore(STORE).get(id);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}
async function putDevice(v){const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(v);r.onsuccess=()=>resolve(v);r.onerror=()=>reject(r.error)})}
export async function listChatIdentities(){const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readonly').objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
export async function ensureChatIdentity(){let id=localDeviceId(),identity=await getDevice(id);if(identity?.privateJwk&&identity?.publicJwk)return identity;const kp=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']);const publicJwk=await crypto.subtle.exportKey('jwk',kp.publicKey);const privateJwk=await crypto.subtle.exportKey('jwk',kp.privateKey);identity={deviceId:id,publicJwk,privateJwk,keyVersion:1,createdAt:new Date().toISOString()};await putDevice(identity);return identity}
export async function publicKeyPayload(){const i=await ensureChatIdentity();return {deviceId:i.deviceId,publicKey:i.publicJwk,keyVersion:i.keyVersion}}
export async function rotateChatIdentity(){const current=await ensureChatIdentity();const kp=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']);const publicJwk=await crypto.subtle.exportKey('jwk',kp.publicKey);const privateJwk=await crypto.subtle.exportKey('jwk',kp.privateKey);const next={...current,publicJwk,privateJwk,keyVersion:Number(current.keyVersion||1)+1,rotatedAt:new Date().toISOString()};await putDevice(next);return next}
async function sharedKey(peerJwk, identity){const id=identity||await ensureChatIdentity();const privateKey=await crypto.subtle.importKey('jwk',id.privateJwk,{name:'ECDH',namedCurve:'P-256'},false,['deriveBits']);const peer=await crypto.subtle.importKey('jwk',peerJwk,{name:'ECDH',namedCurve:'P-256'},false,[]);const bits=await crypto.subtle.deriveBits({name:'ECDH',public:peer},privateKey,256);return crypto.subtle.importKey('raw',bits,{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function encryptFor(text,peer,identity){const key=await sharedKey(peer.public_key||peer.publicKey,identity);const iv=crypto.getRandomValues(new Uint8Array(12));const ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,te.encode(text));return {deviceId:peer.device_id||peer.deviceId,ciphertext:b64(ct),iv:b64(iv),cryptoVersion:2}}
export async function encryptChatPayload(text,peerDevices){const identity=await ensureChatIdentity();const peers=(peerDevices||[]).filter(Boolean);if(!peers.length)throw new Error('Одержувач не має активного E2E-пристрою');const keys=[];for(const peer of peers)keys.push(await encryptFor(text,peer,identity));return {crypto_version:2,sender_device_id:identity.deviceId,sender_key_version:identity.keyVersion,keys}}
export async function encryptChatText(text,peerPublicKey){const identity=await ensureChatIdentity();const x=await encryptFor(text,{public_key:peerPublicKey,device_id:'legacy'},identity);return {ciphertext:x.ciphertext,iv:x.iv,crypto_version:2,sender_device_id:identity.deviceId,sender_key_version:identity.keyVersion,recipient_device_id:'legacy',keys:[x]}}
export async function decryptChatText(message,peerPublicKey,deviceOverride=null){const identity=deviceOverride||await ensureChatIdentity();let keyEntry=null;if(Array.isArray(message?.device_keys))keyEntry=message.device_keys.find(x=>String(x.device_id||x.deviceId)===String(identity.deviceId));if(!keyEntry&&Array.isArray(message?.keys))keyEntry=message.keys.find(x=>String(x.deviceId||x.device_id)===String(identity.deviceId));if(!keyEntry&&message?.ciphertext&&message?.iv)keyEntry={ciphertext:message.ciphertext,iv:message.iv};if(!keyEntry||!peerPublicKey)return message?.text||'';try{const key=await sharedKey(peerPublicKey,identity);const pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:fromB64(keyEntry.iv)},key,fromB64(keyEntry.ciphertext));return td.decode(pt)}catch{return '🔒 Зашифроване повідомлення (цей пристрій не має ключа)'}}
export async function encryptAttachment(file,peerDevices){const bytes=new Uint8Array(await file.arrayBuffer());const peers=(peerDevices||[]).filter(Boolean);if(!peers.length)throw new Error('Немає E2E-пристроїв одержувача');const identity=await ensureChatIdentity();const keys=[];for(const peer of peers){const key=await sharedKey(peer.public_key||peer.publicKey,identity);const iv=crypto.getRandomValues(new Uint8Array(12));const ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,bytes);keys.push({deviceId:peer.device_id||peer.deviceId,ciphertext:b64(ct),iv:b64(iv)})}return {name:String(file.name||'attachment').slice(0,120),mime:String(file.type||'application/octet-stream').slice(0,120),size:bytes.length,keys}}
export async function decryptAttachment(att,peerPublicKey,deviceOverride=null){const identity=deviceOverride||await ensureChatIdentity();const entry=(att?.keys||att?.device_keys||[]).find(x=>String(x.deviceId||x.device_id)===String(identity.deviceId));if(!entry)return null;const key=await sharedKey(peerPublicKey,identity);const bytes=await crypto.subtle.decrypt({name:'AES-GCM',iv:fromB64(entry.iv)},key,fromB64(entry.ciphertext));return new Blob([bytes],{type:att.mime||'application/octet-stream'})}
export function fingerprint(jwk){return crypto.subtle.digest('SHA-256',te.encode(JSON.stringify(jwk))).then(buf=>Array.from(new Uint8Array(buf)).map(x=>x.toString(16).padStart(2,'0')).join('').match(/.{1,4}/g).slice(0,8).join(':'))}
export function trustKey(nick,fp){try{localStorage.setItem('ef-chat-trust:'+String(nick).toLowerCase(),String(fp))}catch{}}
export function trustedKey(nick){try{return localStorage.getItem('ef-chat-trust:'+String(nick).toLowerCase())||''}catch{return''}}
export function untrustKey(nick){try{localStorage.removeItem('ef-chat-trust:'+String(nick).toLowerCase())}catch{}}
