import fs from 'node:fs/promises';
import path from 'node:path';

const TOKEN = process.env.NOTION_TOKEN;
const DATA_SOURCE_ID = process.env.NOTION_DATA_SOURCE_ID || 'f38dba17-bbd6-4f04-9875-030212db4d0a';
const API_VERSION = '2025-09-03';

if (!TOKEN) {
  console.error('Missing NOTION_TOKEN. Create a Notion integration, share the English words database with it, then set NOTION_TOKEN.');
  process.exit(1);
}

async function notionQuery(body) {
  const res = await fetch(`https://api.notion.com/v1/data_sources/${DATA_SOURCE_ID}/query`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${TOKEN}`,
      'Notion-Version': API_VERSION,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(body)
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`Notion API ${res.status}: ${text}`);
  return JSON.parse(text);
}

const all = [];
let cursor;
do {
  const result = await notionQuery({ page_size: 100, ...(cursor ? { start_cursor: cursor } : {}) });
  for (const row of result.results ?? []) {
    const p = row.properties ?? {};
    const title = p.Word?.title?.map(x => x.plain_text).join('') || '';
    const rich = key => p[key]?.rich_text?.map(x => x.plain_text).join('') || '';
    const select = key => p[key]?.select?.name || '';
    const date = p.Added?.date?.start || null;
    if (!title.trim()) continue;
    all.push({
      id: row.id,
      notionUrl: row.url || '',
      word: title.trim(),
      translation: rich('Translation'),
      explanation: rich('Explanation'),
      pronunciation: rich('Pronunciation'),
      examples: rich('Examples'),
      category: select('Category'),
      added: date
    });
  }
  cursor = result.has_more ? result.next_cursor : null;
} while (cursor);

all.sort((a, b) => a.word.localeCompare(b.word, 'en', { sensitivity: 'base' }));

const meta = { dataSourceId: DATA_SOURCE_ID, count: all.length };
const payload = `// AUTO-GENERATED by scripts/sync-notion.mjs — do not edit manually.\nexport const notionWords = ${JSON.stringify(all, null, 2)};\nexport const notionSyncMeta = ${JSON.stringify(meta, null, 2)};\n`;

await fs.writeFile(path.resolve('src/notionWords.generated.js'), payload, 'utf8');
await fs.writeFile(path.resolve('public/notion-sync-meta.json'), JSON.stringify(meta, null, 2), 'utf8');
console.log(`Synced ${all.length} words from Notion.`);
