import React, {useEffect, useMemo, useState} from 'react';
import {BarChart3, BookOpen, Check, CheckCircle2, ChevronRight, Flame, Home, Lock, Menu, Moon, Palette, Play, RotateCcw, Settings, Sun, Target, Trophy, User, Volume2, X, XCircle, Shield, SlidersHorizontal, Brain, Sparkles} from 'lucide-react';
import {words as fallbackWords, rules} from './data';
import {notionWords, notionSyncMeta} from './notionWords.generated';
import { Analytics } from '@vercel/analytics/react';

const words=(notionWords?.length?notionWords:fallbackWords).map(w=>({id:w.id,word:w.word,translation:w.translation||'—',pronunciation:w.pronunciation||'',category:w.category||'Other',explanation:w.explanation||'',example:w.example||(w.examples||'').split('\n')[0]||''}));
const KEY='english-flow-platform-v3';
const VERSION='0.6-beta';
const TODAY=()=>new Date().toISOString().slice(0,10);
const defaultAdmin={lessonSize:10,correctPoints:4,wrongPoints:-2,masteryThreshold:8,shuffleQuestions:false,shuffleAnswers:true,showPronunciation:true,adminPin:'2468'};
const initial={name:'',xp:0,streak:1,dailyGoal:50,todayXp:0,today:TODAY(),mastery:{},attempts:{},history:[],avatar:'🇺🇸',theme:'light',customTheme:{accent:'#22a06b',bg:'#f6f8f6',surface:'#ffffff'},admin:defaultAdmin};
function load(){try{const raw=JSON.parse(localStorage.getItem(KEY)||'null');const s={...initial,...raw,admin:{...defaultAdmin,...(raw?.admin||{})},customTheme:{...initial.customTheme,...(raw?.customTheme||{})}};return s.today===TODAY()?s:{...s,today:TODAY(),todayXp:0,streak:s.streak||1}}catch{return initial}}
function speak(t){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=.9;speechSynthesis.speak(u)}
function playTone(ok){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.type=ok?'sine':'square';o.frequency.setValueAtTime(ok?660:150,c.currentTime);o.frequency.exponentialRampToValueAtTime(ok?980:95,c.currentTime+.22);g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(ok?.13:.08,c.currentTime+.015);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.25);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.27);setTimeout(()=>c.close(),350)}catch{}}
function hashSeed(str){let h=2166136261;for(let i=0;i<str.length;i++)h=Math.imul(h^str.charCodeAt(i),16777619);return h>>>0}
function seededShuffle(arr,seed){const a=[...arr];let s=seed>>>0;for(let i=a.length-1;i>0;i--){s=(Math.imul(s,1664525)+1013904223)>>>0;const j=s%(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
function makeLesson(source,state,mode='learn'){
 const eligible=mode==='review'?source.filter(w=>(state.mastery[w.id]||0)<state.admin.masteryThreshold):source;
 const size=Math.min(state.admin.lessonSize,eligible.length); const base=state.admin.shuffleQuestions?seededShuffle(eligible,hashSeed(TODAY()+mode+state.name)):eligible;
 return base.slice(0,size).map((w,index)=>{const others=source.filter(x=>x.id!==w.id&&x.translation);let opts=[w.translation,...seededShuffle(others,hashSeed(w.id+TODAY())).slice(0,3).map(x=>x.translation)];if(state.admin.shuffleAnswers)opts=seededShuffle(opts,hashSeed(w.id+'answers'));return {...w,options:opts,order:index}});
}
export default function App(){
 const [state,setState]=useState(load); const [page,setPage]=useState(state.name?'dashboard':'onboarding'); const [mobile,setMobile]=useState(false); const [lessonMode,setLessonMode]=useState('learn');
 const save=s=>{setState(s);localStorage.setItem(KEY,JSON.stringify(s))}; const nav=p=>{setPage(p);setMobile(false)};
 useEffect(()=>{document.documentElement.dataset.theme=state.theme;document.documentElement.style.setProperty('--accent',state.theme==='custom'?state.customTheme.accent:'');document.documentElement.style.setProperty('--custom-bg',state.theme==='custom'?state.customTheme.bg:'');document.documentElement.style.setProperty('--custom-surface',state.theme==='custom'?state.customTheme.surface:'')},[state.theme,state.customTheme]);
 const mastery=words.reduce((n,w)=>n+Math.max(0,Math.min(state.admin.masteryThreshold,state.mastery[w.id]||0)),0), max=words.length*state.admin.masteryThreshold, percent=max?Math.round(mastery/max*100):0;
 const startLesson=m=>{setLessonMode(m);nav('lesson')};
 if(page==='onboarding')return <><Onboarding onDone={name=>{save({...state,name});setPage('dashboard')}}/><div className="version-badge">v{VERSION}</div><Analytics /></>;
 const Sidebar=()=> <aside className={'sidebar '+(mobile?'open':'')}><div className="brand"><span className="brand-mark">EF</span><span>English Flow</span></div><div className="nav-section">LEARN</div>{[['dashboard',Home,'Головна'],['learn',Play,'Навчання'],['vocabulary',BookOpen,'Слова'],['review',RotateCcw,'Повторення']].map(([id,I,t])=><button className={'nav '+(page===id?'active':'')} onClick={()=>nav(id)} key={id}><I size={18}/>{t}</button>)}<div className="nav-section">TRACK</div>{[['stats',BarChart3,'Статистика'],['leaderboard',Trophy,'Рейтинг']].map(([id,I,t])=><button className={'nav '+(page===id?'active':'')} onClick={()=>nav(id)} key={id}><I size={18}/>{t}</button>)}<div className="nav-section">ACCOUNT</div><button className={'nav '+(page==='profile'?'active':'')} onClick={()=>nav('profile')}><User size={18}/>Профіль</button><button className={'nav '+(page==='admin'?'active':'')} onClick={()=>nav('admin')}><Shield size={18}/>Адмін-панель</button></aside>;
 const Layout=({children})=><div className="app"><Sidebar/><main className="main"><header><button className="icon mobile-only" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button><div className="header-user"><span className="avatar-mini">{state.avatar}</span><div><b>{state.name}</b><span className="muted"> · English Flow</span></div></div><div className="header-stats"><span>🔥 {state.streak}</span><span>⚡ {state.xp} XP</span></div></header>{children}<nav className="mobile-nav">{[['dashboard',Home,'Головна'],['learn',Play,'Вчити'],['vocabulary',BookOpen,'Слова'],['stats',BarChart3,'Стата'],['profile',User,'Профіль']].map(([id,I,t])=><button className={page===id?'active':''} onClick={()=>nav(id)} key={id}><I size={18}/><span>{t}</span></button>)}</nav></main></div>;
 return <><Layout>{page==='dashboard'&&<Dashboard/>}{page==='learn'&&<Learn/>}{page==='vocabulary'&&<Vocabulary/>}{page==='review'&&<Review/>}{page==='stats'&&<Stats/>}{page==='leaderboard'&&<Leaderboard/>}{page==='profile'&&<Profile/>}{page==='admin'&&<Admin/>}{page==='lesson'&&<Lesson mode={lessonMode}/>}</Layout><div className="version-badge">v{VERSION}</div><Analytics /></>;
 function Dashboard(){const learned=words.filter(w=>(state.mastery[w.id]||0)>=state.admin.masteryThreshold).length;return <section><div className="hero"><div><span className="eyebrow"><Sparkles size={14}/> TODAY</span><h1>Привіт, {state.name} 👋</h1><p>Вчи англійську короткими вправами та бач свій реальний прогрес.</p><button className="primary" onClick={()=>startLesson('learn')}>Почати урок <Play size={16}/></button></div><div className="hero-ring"><strong>{percent}%</strong><span>mastery</span></div></div><div className="grid stats"><Card icon={<Target/>} title="Сьогодні" value={`${state.todayXp}/${state.dailyGoal} XP`} sub="денна ціль"/><Card icon={<Flame/>} title="Серія" value={`${state.streak} днів`} sub="поспіль"/><Card icon={<Brain/>} title="Вивчено" value={learned} sub={`із ${words.length} слів`}/><Card icon={<Trophy/>} title="XP" value={state.xp} sub="загалом"/></div><div className="grid two"><div className="card"><div className="section-row"><div><h2>Словниковий прогрес</h2><p className="muted">8 правильних відповідей на слово = вивчено.</p></div><strong className="big-percent">{percent}%</strong></div><Progress value={percent}/></div><div className="card next-card"><h2>Що далі?</h2><p>Нові слова → практика → повторення → автоматичне закріплення.</p><button className="secondary" onClick={()=>startLesson('review')}>Повторити слова <ChevronRight size={16}/></button></div></div></section>}
 function Learn(){return <section><Title title="Навчання" text="Обирай режим і проходь стабільні уроки без стрибків питань."/><div className="grid two lesson-grid"><div className="card lesson-card"><div className="lesson-icon">⚡</div><span className="pill">VOCABULARY</span><h2>Vocabulary Sprint</h2><p className="muted">{Math.min(state.admin.lessonSize,words.length)} питань · +{state.admin.correctPoints} / {state.admin.wrongPoints} XP · 8 правильних = вивчено</p><button className="primary" onClick={()=>startLesson('learn')}>Почати <Play size={16}/></button></div><div className="card lesson-card"><div className="lesson-icon">🔁</div><span className="pill">REVIEW</span><h2>Smart Review</h2><p className="muted">Повторює слова, які ще не досягли {state.admin.masteryThreshold}/{state.admin.masteryThreshold}.</p><button className="secondary" onClick={()=>startLesson('review')}>Повторення <RotateCcw size={16}/></button></div></div><div className="card"><h2>Граматика</h2>{rules.map(r=><div className="rule" key={r.id}><b>{r.title}</b><span>{r.explanation}</span></div>)}</div></section>}
 function Vocabulary(){const[q,setQ]=useState('');const f=words.filter(w=>(w.word+' '+w.translation+' '+w.category).toLowerCase().includes(q.toLowerCase()));return <section><Title title="Слова" text={`${words.length} слів синхронізовано з твоєї бази.`}/><input className="search" placeholder="Пошук слова, перекладу або категорії..." value={q} onChange={e=>setQ(e.target.value)}/><div className="word-list">{f.map(w=>{const m=state.mastery[w.id]||0;return <div className="word card" key={w.id}><div className="word-main"><div className="word-line"><h3>{w.word}</h3><span className="mastery-badge">{m}/{state.admin.masteryThreshold}</span></div><span className="muted">{w.pronunciation} · {w.category}</span><p>{w.translation}</p><Progress value={m/state.admin.masteryThreshold*100}/></div><button className="icon" onClick={()=>speak(w.word)} aria-label="Прослухати"><Volume2/></button></div>})}</div></section>}
 function Review(){const due=words.filter(w=>(state.mastery[w.id]||0)<state.admin.masteryThreshold).sort((a,b)=>(state.mastery[a.id]||0)-(state.mastery[b.id]||0)).slice(0,20);return <section><Title title="Повторення" text="Система підтягує слова з найнижчим mastery."/><div className="card review-hero"><div><span className="eyebrow">SMART REVIEW</span><h2>{due.length} слів потребують практики</h2><p className="muted">Після 8 правильних відповідей слово переходить у «Вивчено».</p></div><button className="primary" onClick={()=>startLesson('review')} disabled={!due.length}>Почати <Play size={16}/></button></div><div className="word-list compact">{due.slice(0,8).map(w=><div className="word card" key={w.id}><div><b>{w.word}</b><span className="muted"> · {w.translation}</span></div><strong>{state.mastery[w.id]||0}/{state.admin.masteryThreshold}</strong></div>)}</div></section>}
 function Stats(){const total=state.history.length,correct=state.history.filter(x=>x.correct).length,accuracy=total?Math.round(correct/total*100):0,learned=words.filter(w=>(state.mastery[w.id]||0)>=state.admin.masteryThreshold).length,learning=words.filter(w=>{const m=state.mastery[w.id]||0;return m>0&&m<state.admin.masteryThreshold}).length;return <section><Title title="Статистика" text="Не тільки XP — дивись, як реально росте словниковий запас."/><div className="grid stats"><Card title="XP" value={state.xp} sub="всього"/><Card title="Точність" value={`${accuracy}%`} sub={`${correct} правильних із ${total}`}/><Card title="Вивчено" value={learned} sub={`${learning} у процесі`}/><Card title="Спроб" value={total} sub="відповідей"/></div><div className="card"><div className="section-row"><div><h2>Загальне mastery</h2><p className="muted">Середній прогрес по всіх {words.length} словах.</p></div><strong className="big-percent">{percent}%</strong></div><Progress value={percent}/><div className="stat-breakdown"><span>🟢 Вивчено: {learned}</span><span>🟡 В процесі: {learning}</span><span>⚪ Нові: {Math.max(0,words.length-learned-learning)}</span></div></div><div className="card"><h2>Останні результати</h2>{!total?<p className="muted">Пройди перший урок — тут з'явиться історія.</p>:<div className="history-list">{state.history.slice(-15).reverse().map((h,i)=><div className="history-row" key={i}><span>{words.find(w=>w.id===h.word)?.word||'Word'}</span><b className={h.correct?'success-text':'error-text'}>{h.correct?`+${h.points}`:`${h.points}`} XP</b></div>)}</div>}</div></section>}
 function Leaderboard(){const base=[['Sofia',840],['Daniel',720],['Marta',510],['Alex',430],['Emma',380]];const people=[...base.filter(p=>p[0]!==state.name),[state.name,state.xp]].sort((a,b)=>b[1]-a[1]);const rank=people.findIndex(p=>p[0]===state.name)+1;return <section><Title title="Рейтинг" text="Локальний demo-лідерборд. Реальний multiplayer потребує backend."/><div className="leader-summary card"><div><span>Позиція</span><strong>#{rank}</strong></div><div><span>XP</span><strong>{state.xp}</strong></div><div><span>До наступного</span><strong>{rank>1?Math.max(0,people[rank-2][1]-state.xp+1):'—'}</strong></div></div><div className="card leaderboard">{people.map((p,i)=><div className={'rank '+(p[0]===state.name?'me':'')} key={p[0]}><strong>{i<3?['🥇','🥈','🥉'][i]:`#${i+1}`}</strong><span>{p[0]} {p[0]===state.name&&<small>Ти</small>}</span><b>{p[1]} XP</b></div>)}</div></section>}
 function Profile(){const[n,setN]=useState(state.name),[g,setG]=useState(state.dailyGoal),[theme,setTheme]=useState(state.theme),[accent,setAccent]=useState(state.customTheme.accent),[bg,setBg]=useState(state.customTheme.bg),[surface,setSurface]=useState(state.customTheme.surface),[msg,setMsg]=useState('');const update=()=>{save({...state,name:n.trim()||state.name,dailyGoal:Math.max(10,Math.min(500,Number(g)||50)),theme,customTheme:{accent,bg,surface}});setMsg('Зміни збережено ✓');setTimeout(()=>setMsg(''),1600)};return <section><Title title="Профіль та налаштування" text="Керуй акаунтом, темою та навчальною ціллю."/><div className="grid two"><div className="card profile-card"><div className="profile-avatar">{state.avatar}</div><div className="profile-fields"><label>Ім'я</label><input className="search" value={n} onChange={e=>setN(e.target.value)}/><label>Денна ціль XP</label><input className="search" type="number" min="10" max="500" value={g} onChange={e=>setG(e.target.value)}/><button className="primary" onClick={update}><Check size={17}/> Зберегти</button>{msg&&<span className="saved-message">{msg}</span>}</div></div><div className="card"><div className="section-row"><h2><Palette size={20}/> Тема</h2><span className="pill">{theme}</span></div><div className="theme-buttons"><button className={theme==='light'?'theme active':''} onClick={()=>setTheme('light')}><Sun/> Світла</button><button className={theme==='dark'?'theme active':''} onClick={()=>setTheme('dark')}><Moon/> Темна</button><button className={theme==='custom'?'theme active':''} onClick={()=>setTheme('custom')}><Palette/> Custom</button></div>{theme==='custom'&&<div className="color-grid"><label>Акцент <input type="color" value={accent} onChange={e=>setAccent(e.target.value)}/></label><label>Фон <input type="color" value={bg} onChange={e=>setBg(e.target.value)}/></label><label>Картки <input type="color" value={surface} onChange={e=>setSurface(e.target.value)}/></label></div>}</div></div><div className="card settings-card"><h2><Settings size={20}/> Система</h2><p className="muted">Дані зберігаються локально в цьому браузері. Notion синхронізує {notionSyncMeta.count||words.length} слів.</p><button className="danger" onClick={()=>{if(confirm('Скинути весь локальний прогрес?')){localStorage.removeItem(KEY);location.reload()}}}>Скинути прогрес</button></div></section>}
 function Admin(){const[a,setA]=useState(state.admin),[saved,setSaved]=useState(false);const update=(k,v)=>setA(x=>({...x,[k]:v}));const saveAdmin=()=>{save({...state,admin:{...a,lessonSize:Math.max(3,Math.min(50,Number(a.lessonSize)||10)),correctPoints:Number(a.correctPoints)||4,wrongPoints:Number(a.wrongPoints)||-2,masteryThreshold:Math.max(1,Math.min(20,Number(a.masteryThreshold)||8))}});setSaved(true);setTimeout(()=>setSaved(false),1500)};return <section><Title title="Адмін-панель" text="Керуйте правилами навчання та поведінкою платформи."/><div className="admin-warning"><Lock size={18}/><span>Це локальна адмін-панель для static GitHub Pages. Вона не є серверним захистом.</span></div><div className="grid two"><div className="card"><h2><SlidersHorizontal size={20}/> Правила уроку</h2><div className="form-grid"><label>Питань у уроці<input type="number" min="3" max="50" value={a.lessonSize} onChange={e=>update('lessonSize',e.target.value)}/></label><label>За правильну відповідь<input type="number" value={a.correctPoints} onChange={e=>update('correctPoints',e.target.value)}/></label><label>За неправильну<input type="number" value={a.wrongPoints} onChange={e=>update('wrongPoints',e.target.value)}/></label><label>Правильних для «Вивчено»<input type="number" min="1" max="20" value={a.masteryThreshold} onChange={e=>update('masteryThreshold',e.target.value)}/></label></div><Toggle label="Перемішувати питання" value={a.shuffleQuestions} onChange={v=>update('shuffleQuestions',v)}/><Toggle label="Перемішувати варіанти" value={a.shuffleAnswers} onChange={v=>update('shuffleAnswers',v)}/><Toggle label="Показувати вимову" value={a.showPronunciation} onChange={v=>update('showPronunciation',v)}/></div><div className="card"><h2><Shield size={20}/> Дані та керування</h2><p className="muted">Поточний прогрес: {state.xp} XP · {state.history.length} відповідей · {Object.keys(state.mastery).length} слів мають прогрес.</p><button className="secondary" onClick={()=>{if(confirm('Очистити тільки історію відповідей?'))save({...state,history:[]})}}>Очистити історію</button><button className="secondary" onClick={()=>{if(confirm('Обнулити mastery всіх слів?'))save({...state,mastery:{},attempts:{}})}}>Обнулити mastery</button><button className="secondary" onClick={()=>{if(confirm('Обнулити XP?'))save({...state,xp:0,todayXp:0})}}>Обнулити XP</button><div className="admin-note"><b>Notion:</b> {notionSyncMeta.count||words.length} слів · остання синхронізація: {notionSyncMeta.syncedAt||'через GitHub Actions'}</div></div></div><div className="card save-admin"><button className="primary" onClick={saveAdmin}><Check/> Застосувати налаштування</button>{saved&&<span className="saved-message">Налаштування застосовано ✓</span>}</div></section>}
 function Lesson({mode}){const[items]=useState(()=>makeLesson(words,state,mode));const[index,setIndex]=useState(0),[picked,setPicked]=useState(null),[done,setDone]=useState(false),[flash,setFlash]=useState(''),[scorePop,setScorePop]=useState(null);const w=items[index];if(done||!w)return <section><div className="complete card"><CheckCircle2 size={68}/><span className="eyebrow">LESSON COMPLETE</span><h1>Урок завершено 🎉</h1><p>Ти пройшов {items.length} із {items.length} вправ.</p><div className="completion-stats"><span><b>{items.filter(x=>{const h=[...state.history].reverse().find(h=>h.word===x.id);return h&&h.correct}).length}</b> вправ</span><span><b>{state.xp}</b> XP загалом</span></div><button className="primary" onClick={()=>nav('dashboard')}>На головну <ChevronRight size={16}/></button></div></section>;
 const answer=o=>{if(picked)return;const ok=o===w.translation;const points=ok?state.admin.correctPoints:state.admin.wrongPoints;const current=state.mastery[w.id]||0;const nextMastery=Math.max(0,current+(ok?1:0));const attempts={...state.attempts,[w.id]:(state.attempts[w.id]||0)+1};const s={...state,mastery:{...state.mastery,[w.id]:nextMastery},attempts,xp:state.xp+points,todayXp:state.todayXp+points,history:[...state.history,{word:w.id,correct:ok,points,date:new Date().toISOString()}].slice(-1000)};setPicked(o);setFlash(ok?'correct':'wrong');setScorePop({pts:points,ok,key:Date.now()});playTone(ok);save(s);setTimeout(()=>setFlash(''),850);setTimeout(()=>setScorePop(null),900)};
 const next=()=>index===items.length-1?setDone(true):(setIndex(index+1),setPicked(null),setScorePop(null),setFlash('')); const correct=picked===w.translation; const masteryNow=state.mastery[w.id]||0;return <section><button className="back" onClick={()=>nav(mode==='review'?'review':'learn')}>← Назад</button><div className="lesson-progress-row"><Progress value={index/items.length*100}/><span>{index+1}/{items.length}</span></div><div className={'lesson question card '+(flash?'flash-'+flash:'')}><div className="lesson-top"><span className="pill">{mode==='review'?'REVIEW':'VOCABULARY'}</span><span className={'points '+(picked?(correct?'positive':'negative'):'')}>{picked?(correct?`+${state.admin.correctPoints}`:`${state.admin.wrongPoints}`):'XP'}</span>{scorePop&&<span key={scorePop.key} className={'score-float '+(scorePop.ok?'up':'down')}>{scorePop.pts>0?'+':''}{scorePop.pts}</span>}</div><h1>Що означає <em>{w.word}</em>?</h1>{state.admin.showPronunciation&&<p className="muted">{w.pronunciation} · {w.category}</p>}<button className="speak" onClick={()=>speak(w.word)}><Volume2/> Прослухати</button><div className="options">{w.options.map((o,j)=><button key={`${w.id}-${j}`} disabled={!!picked} className={'option '+(picked?(o===w.translation?'correct':o===picked?'wrong':'dimmed'):'')} onClick={()=>answer(o)}>{o}</button>)}</div>{picked&&<div className={'feedback '+(correct?'feedback-correct':'feedback-wrong')}><div className="feedback-icon">{correct?<CheckCircle2/>:<XCircle/>}</div><div className="feedback-copy"><strong>{correct?'Правильно!':'Неправильно'}</strong><span>{correct?`+${state.admin.correctPoints} XP`:`${state.admin.wrongPoints} XP · Правильна відповідь: ${w.translation}`}</span>{w.example&&<small>{w.example}</small>}<small>Mastery: {masteryNow}/{state.admin.masteryThreshold}{masteryNow>=state.admin.masteryThreshold?' · Вивчено ✓':''}</small></div><button className="primary" onClick={next}>{index===items.length-1?'Завершити':'Далі'} <ChevronRight size={16}/></button></div>}</div></section>}
}
function Onboarding({onDone}){const[n,setN]=useState('');return <div className="onboarding"><div className="welcome card"><div className="logo">EF</div><span className="eyebrow">ENGLISH LEARNING PLATFORM</span><h1>English Flow</h1><p className="muted">Повноцінний тренажер англійської: слова, повторення, XP, mastery та статистика.</p><h2>Як тебе звати?</h2><input autoFocus className="search" placeholder="Наприклад, Mikola" value={n} onChange={e=>setN(e.target.value)} onKeyDown={e=>e.key==='Enter'&&n.trim()&&onDone(n.trim())}/><button className="primary full" disabled={!n.trim()} onClick={()=>onDone(n.trim())}>Почати навчання <ChevronRight size={17}/></button></div></div>}
function Title({title,text}){return <div className="title"><h1>{title}</h1><p className="muted">{text}</p></div>}
function Card({icon,title,value,sub}){return <div className="card stat"><div className="stat-top">{icon}<span>{title}</span></div><strong>{value}</strong><small>{sub}</small></div>}
function Progress({value}){return <div className="progress"><i style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div>}
function Toggle({label,value,onChange}){return <label className="toggle-row"><span>{label}</span><button type="button" className={'switch '+(value?'on':'')} onClick={()=>onChange(!value)}><i/></button></label>}
