export const words = [
{id:1,word:'achieve',translation:'досягати',pronunciation:'/əˈtʃiːv/',category:'Verb',level:'B1',explanation:'to successfully reach a goal',example:'She worked hard to achieve her goal.',exampleUa:'Вона багато працювала, щоб досягти своєї мети.'},
{id:2,word:'improve',translation:'покращувати',pronunciation:'/ɪmˈpruːv/',category:'Verb',level:'B1',explanation:'to make something better',example:'I want to improve my English.',exampleUa:'Я хочу покращити свою англійську.'},
{id:3,word:'although',translation:'хоча',pronunciation:'/ɔːlˈðoʊ/',category:'Conjunction',level:'B1',explanation:'used to introduce a contrast',example:'Although it was late, we kept working.',exampleUa:'Хоча було пізно, ми продовжили працювати.'},
{id:4,word:'reliable',translation:'надійний',pronunciation:'/rɪˈlaɪəbəl/',category:'Adjective',level:'B2',explanation:'able to be trusted',example:'He is a reliable person.',exampleUa:'Він надійна людина.'},
{id:5,word:'opportunity',translation:'можливість',pronunciation:'/ˌɑːpərˈtuːnəti/',category:'Noun',level:'B1',explanation:'a favorable chance',example:'This job is a great opportunity.',exampleUa:'Ця робота — чудова можливість.'},
{id:6,word:'avoid',translation:'уникати',pronunciation:'/əˈvɔɪd/',category:'Verb',level:'B1',explanation:'to stay away from something',example:'Try to avoid unnecessary stress.',exampleUa:'Намагайся уникати зайвого стресу.'},
{id:7,word:'eventually',translation:'зрештою',pronunciation:'/ɪˈventʃuəli/',category:'Adverb',level:'B2',explanation:'in the end, after some time',example:'Eventually, everything worked out.',exampleUa:'Зрештою все вийшло.'},
{id:8,word:'confidence',translation:'впевненість',pronunciation:'/ˈkɑːnfɪdəns/',category:'Noun',level:'B2',explanation:'belief in your own abilities',example:'Practice gave me more confidence.',exampleUa:'Практика дала мені більше впевненості.'},
{id:9,word:'require',translation:'вимагати',pronunciation:'/rɪˈkwaɪər/',category:'Verb',level:'B2',explanation:'to need something',example:'The job requires experience.',exampleUa:'Для цієї роботи потрібен досвід.'},
{id:10,word:'significant',translation:'значний',pronunciation:'/sɪɡˈnɪfɪkənt/',category:'Adjective',level:'B2',explanation:'important or large enough',example:'There was a significant improvement.',exampleUa:'Було значне покращення.'},
{id:11,word:'benefit',translation:'користь',pronunciation:'/ˈbenɪfɪt/',category:'Noun',level:'B1',explanation:'an advantage',example:'Exercise has many benefits.',exampleUa:'Спорт має багато переваг.'},
{id:12,word:'challenge',translation:'виклик',pronunciation:'/ˈtʃælɪndʒ/',category:'Noun',level:'B1',explanation:'a difficult task',example:'Learning a language is a challenge.',exampleUa:'Вивчення мови — це виклик.'},
{id:13,word:'develop',translation:'розвивати',pronunciation:'/dɪˈveləp/',category:'Verb',level:'B1',explanation:'to grow or improve',example:'She wants to develop new skills.',exampleUa:'Вона хоче розвинути нові навички.'},
{id:14,word:'environment',translation:'довкілля',pronunciation:'/ɪnˈvaɪrənmənt/',category:'Noun',level:'B1',explanation:'the natural world or surroundings',example:'We must protect the environment.',exampleUa:'Ми повинні захищати довкілля.'},
{id:15,word:'essential',translation:'необхідний',pronunciation:'/ɪˈsenʃəl/',category:'Adjective',level:'B1',explanation:'absolutely necessary',example:'Water is essential for life.',exampleUa:'Вода необхідна для життя.'},
{id:16,word:'flexible',translation:'гнучкий',pronunciation:'/ˈfleksəbəl/',category:'Adjective',level:'B1',explanation:'able to change easily',example:'Our schedule is flexible.',exampleUa:'Наш графік гнучкий.'},
{id:17,word:'generate',translation:'генерувати',pronunciation:'/ˈdʒenəreɪt/',category:'Verb',level:'B2',explanation:'to produce or create',example:'Solar panels generate electricity.',exampleUa:'Сонячні панелі генерують електроенергію.'},
{id:18,word:'however',translation:'однак',pronunciation:'/haʊˈevər/',category:'Adverb',level:'B1',explanation:'used to introduce a contrast',example:'It was hard; however, we finished.',exampleUa:'Було важко; однак ми закінчили.'},
{id:19,word:'identify',translation:'визначати',pronunciation:'/aɪˈdentɪfaɪ/',category:'Verb',level:'B2',explanation:'to recognize or name',example:'Can you identify the problem?',exampleUa:'Чи можеш визначити проблему?'},
{id:20,word:'justify',translation:'виправдовувати',pronunciation:'/ˈdʒʌstɪfaɪ/',category:'Verb',level:'B2',explanation:'to show that something is right',example:'How can you justify this decision?',exampleUa:'Як ти можеш виправдати це рішення?'},
{id:21,word:'knowledge',translation:'знання',pronunciation:'/ˈnɑːlɪdʒ/',category:'Noun',level:'B1',explanation:'information and understanding',example:'Knowledge is power.',exampleUa:'Знання — сила.'},
{id:22,word:'maintain',translation:'підтримувати',pronunciation:'/meɪnˈteɪn/',category:'Verb',level:'B2',explanation:'to keep something in good condition',example:'It is hard to maintain a balance.',exampleUa:'Важко підтримувати баланс.'},
{id:23,word:'necessary',translation:'необхідний',pronunciation:'/ˈnesəseri/',category:'Adjective',level:'B1',explanation:'needed',example:'Is it necessary to come early?',exampleUa:'Чи необхідно приходити рано?'},
{id:24,word:'obtain',translation:'отримувати',pronunciation:'/əbˈteɪn/',category:'Verb',level:'B2',explanation:'to get something',example:'You can obtain a visa online.',exampleUa:'Візу можна отримати онлайн.'},
{id:25,word:'persuade',translation:'переконувати',pronunciation:'/pərˈsweɪd/',category:'Verb',level:'B2',explanation:'to make someone agree',example:'She persuaded me to join.',exampleUa:'Вона переконала мене приєднатися.'},
{id:26,word:'quality',translation:'якість',pronunciation:'/ˈkwɑːləti/',category:'Noun',level:'B1',explanation:'how good something is',example:'We focus on quality, not quantity.',exampleUa:'Ми зосереджуємось на якості, не на кількості.'},
{id:27,word:'relevant',translation:'релевантний',pronunciation:'/ˈreləvənt/',category:'Adjective',level:'B2',explanation:'closely connected',example:'Your question is very relevant.',exampleUa:'Твоє питання дуже доречне.'},
{id:28,word:'source',translation:'джерело',pronunciation:'/sɔːrs/',category:'Noun',level:'B1',explanation:'where something comes from',example:'What is the source of this data?',exampleUa:'Яке джерело цих даних?'},
{id:29,word:'tend',translation:'мати тенденцію',pronunciation:'/tend/',category:'Verb',level:'B2',explanation:'to be likely to do something',example:'I tend to wake up early.',exampleUa:'Я маю тенденцію прокидатися рано.'},
{id:30,word:'unique',translation:'унікальний',pronunciation:'/juˈniːk/',category:'Adjective',level:'B1',explanation:'being the only one of its kind',example:'Each person is unique.',exampleUa:'Кожна людина унікальна.'},
{id:31,word:'variety',translation:'різноманітність',pronunciation:'/vəˈraɪəti/',category:'Noun',level:'B1',explanation:'many different types',example:'There is a variety of options.',exampleUa:'Є різноманітність варіантів.'},
{id:32,word:'aware',translation:'обізнаний',pronunciation:'/əˈwer/',category:'Adjective',level:'B1',explanation:'knowing about something',example:'Are you aware of the risk?',exampleUa:'Ти обізнаний про ризик?'},
{id:33,word:'brief',translation:'короткий',pronunciation:'/briːf/',category:'Adjective',level:'B1',explanation:'short in time or length',example:'Please give a brief summary.',exampleUa:'Будь ласка, дай короткий виклад.'},
{id:34,word:'consider',translation:'розглядати',pronunciation:'/kənˈsɪdər/',category:'Verb',level:'B1',explanation:'to think carefully about',example:'Consider all options first.',exampleUa:'Спочатку розглянь усі варіанти.'},
{id:35,word:'demand',translation:'попит',pronunciation:'/dɪˈmænd/',category:'Noun',level:'B2',explanation:'a strong need or request',example:'There is high demand for this skill.',exampleUa:'На цю навичку високий попит.'},
{id:36,word:'efficient',translation:'ефективний',pronunciation:'/ɪˈfɪʃənt/',category:'Adjective',level:'B2',explanation:'working well without waste',example:'This method is more efficient.',exampleUa:'Цей метод ефективніший.'},
{id:37,word:'feature',translation:'особливість',pronunciation:'/ˈfiːtʃər/',category:'Noun',level:'B1',explanation:'an important part or quality',example:'The main feature is speed.',exampleUa:'Головна особливість — швидкість.'},
{id:38,word:'global',translation:'глобальний',pronunciation:'/ˈɡloʊbəl/',category:'Adjective',level:'B1',explanation:'relating to the whole world',example:'This is a global issue.',exampleUa:'Це глобальна проблема.'},
{id:39,word:'impact',translation:'вплив',pronunciation:'/ˈɪmpækt/',category:'Noun',level:'B1',explanation:'a strong effect',example:'The impact was huge.',exampleUa:'Вплив був величезний.'},
{id:40,word:'major',translation:'основний',pronunciation:'/ˈmeɪdʒər/',category:'Adjective',level:'B1',explanation:'very important or large',example:'This is a major change.',exampleUa:'Це основна зміна.'},
{id:41,word:'negotiate',translation:'вести переговори',pronunciation:'/nɪˈɡoʊʃieɪt/',category:'Verb',level:'B2',explanation:'to discuss to reach agreement',example:'They negotiated a better deal.',exampleUa:'Вони узгодили кращу угоду.'},
{id:42,word:'obvious',translation:'очевидний',pronunciation:'/ˈɑːbviəs/',category:'Adjective',level:'B1',explanation:'easy to see or understand',example:'The answer is obvious.',exampleUa:'Відповідь очевидна.'},
{id:43,word:'prefer',translation:'віддавати перевагу',pronunciation:'/prɪˈfɜːr/',category:'Verb',level:'B1',explanation:'to like more than another',example:'I prefer tea to coffee.',exampleUa:'Я віддаю перевагу чаю, а не каві.'},
{id:44,word:'reduce',translation:'зменшувати',pronunciation:'/rɪˈduːs/',category:'Verb',level:'B1',explanation:'to make smaller',example:'We need to reduce costs.',exampleUa:'Нам треба зменшити витрати.'},
{id:45,word:'succeed',translation:'досягати успіху',pronunciation:'/səkˈsiːd/',category:'Verb',level:'B1',explanation:'to achieve what you want',example:'If you work hard, you will succeed.',exampleUa:'Якщо працюватимеш наполегливо, досягнеш успіху.'},
{id:46,word:'therefore',translation:'тому',pronunciation:'/ˈðerfɔːr/',category:'Adverb',level:'B2',explanation:'for that reason',example:'It was raining; therefore we stayed.',exampleUa:'Йшов дощ; тому ми залишились.'},
{id:47,word:'valuable',translation:'цінний',pronunciation:'/ˈvæljuəbəl/',category:'Adjective',level:'B1',explanation:'worth a lot',example:'Your advice is valuable.',exampleUa:'Твоя порада цінна.'},
{id:48,word:'waste',translation:'марнувати',pronunciation:'/weɪst/',category:'Verb',level:'B1',explanation:'to use carelessly',example:"Don't waste your time.",exampleUa:'Не марнуй час.'},
{id:49,word:'approach',translation:'підхід',pronunciation:'/əˈproʊtʃ/',category:'Noun',level:'B2',explanation:'a way of dealing with something',example:'We need a new approach.',exampleUa:'Нам потрібен новий підхід.'},
{id:50,word:'complex',translation:'складний',pronunciation:'/kəmˈpleks/',category:'Adjective',level:'B1',explanation:'having many parts',example:'It is a complex problem.',exampleUa:'Це складна проблема.'},
];

export const rules = [
{id:1,title:'Present Perfect',category:'Tense',explanation:'have/has + past participle for past actions connected to the present.',example:'I have finished my homework.'},
{id:2,title:'Present Perfect vs Past Simple',category:'Tenses',explanation:'Use Past Simple for finished past time; Present Perfect when the exact time is not important.',example:'I went there yesterday. / I have been there before.'},
{id:3,title:'Conditionals',category:'Grammar',explanation:'Use if-clauses to talk about real, possible, or hypothetical situations.',example:'If I have time, I will call you.'},
{id:4,title:'Modal verbs',category:'Grammar',explanation:'can, could, should, must, might express ability, advice, obligation or possibility.',example:'You should practice every day.'},
{id:5,title:'Articles',category:'Grammar',explanation:'Use a/an for a non-specific singular noun and the for something specific.',example:'I saw a dog. The dog was friendly.'}
];

export const BADGES = [
{id:'first_steps',title:'Перші кроки',desc:'Пройди перший урок',icon:'🌱'},
{id:'streak_3',title:'3 дні поспіль',desc:'Streak ≥ 3',icon:'🔥'},
{id:'streak_7',title:'Тиждень вогню',desc:'Streak ≥ 7',icon:'🔥'},
{id:'words_20',title:'20 слів',desc:'Вивчи 20 слів',icon:'📚'},
{id:'words_50',title:'50 слів',desc:'Вивчи 50 слів',icon:'🏆'},
{id:'xp_500',title:'500 XP',desc:'Набери 500 XP',icon:'⚡'},
{id:'perfect_lesson',title:'Без помилок',desc:'Урок без жодної помилки',icon:'💎'},
{id:'dictation',title:'Диктант',desc:'Пройди режим диктанту',icon:'✍️'},
{id:'match_master',title:'Match Master',desc:'Виграй Match-гру',icon:'🎯'},
];