export const words = [
{id:1,word:'achieve',translation:'досягати',pronunciation:'/əˈtʃiːv/',category:'Verb',level:'B1',explanation:'to successfully reach a goal',example:'She worked hard to achieve her goal.',exampleUa:'Вона багато працювала, щоб досягти своєї мети.'},
{id:2,word:'improve',translation:'покращувати',pronunciation:'/ɪmˈpruːv/',category:'Verb',level:'B1',explanation:'to make something better',example:'I want to improve my English.',exampleUa:'Я хочу покращити свою англійську.'},
{id:3,word:'although',translation:'хоча',pronunciation:'/ɔːlˈðoʊ/',category:'Conjunction',level:'B1',explanation:'used to introduce a contrast',example:'Although it was late, we kept working.',exampleUa:'Хоча було пізно, ми продовжили працювати.'},
{id:4,word:'reliable',translation:'надійний',pronunciation:'/rɪˈlaɪəbəl/',category:'Adjective',level:'B2',explanation:'able to be trusted or depended on',example:'He is a reliable person.',exampleUa:'Він надійна людина.'},
{id:5,word:'opportunity',translation:'можливість',pronunciation:'/ˌɑːpərˈtuːnəti/',category:'Noun',level:'B1',explanation:'a favorable chance to do something',example:'This job is a great opportunity.',exampleUa:'Ця робота — чудова можливість.'},
{id:6,word:'avoid',translation:'уникати',pronunciation:'/əˈvɔɪd/',category:'Verb',level:'B1',explanation:'to stay away from something',example:'Try to avoid unnecessary stress.',exampleUa:'Намагайся уникати зайвого стресу.'},
{id:7,word:'eventually',translation:'зрештою',pronunciation:'/ɪˈventʃuəli/',category:'Adverb',level:'B2',explanation:'in the end, after some time',example:'Eventually, everything worked out.',exampleUa:'Зрештою все вийшло.'},
{id:8,word:'confidence',translation:'впевненість',pronunciation:'/ˈkɑːnfɪdəns/',category:'Noun',level:'B2',explanation:'belief in your own abilities',example:'Practice gave me more confidence.',exampleUa:'Практика дала мені більше впевненості.'},
{id:9,word:'require',translation:'вимагати',pronunciation:'/rɪˈkwaɪər/',category:'Verb',level:'B2',explanation:'to need something',example:'The job requires experience.',exampleUa:'Для цієї роботи потрібен досвід.'},
{id:10,word:'likely',translation:'ймовірний',pronunciation:'/ˈlaɪkli/',category:'Adjective',level:'B2',explanation:'probable or expected',example:'It is likely to rain.',exampleUa:'Ймовірно, буде дощ.'},
{id:11,word:'benefit',translation:'користь / перевага',pronunciation:'/ˈbenɪfɪt/',category:'Noun/Verb',level:'B1',explanation:'a useful effect or advantage',example:'Exercise has many health benefits.',exampleUa:'Фізичні вправи мають багато переваг для здоров’я.'},
{id:12,word:'accurate',translation:'точний',pronunciation:'/ˈækjərət/',category:'Adjective',level:'B2',explanation:'correct and without mistakes',example:'Please give me accurate information.',exampleUa:'Будь ласка, дай мені точну інформацію.'},
{id:13,word:'handle',translation:'впоратися / обробляти',pronunciation:'/ˈhændəl/',category:'Verb',level:'B2',explanation:'to deal with a situation or task',example:'Can you handle this problem?',exampleUa:'Ти можеш впоратися з цією проблемою?'},
{id:14,word:'despite',translation:'попри',pronunciation:'/dɪˈspaɪt/',category:'Preposition',level:'B2',explanation:'without being affected by something',example:'Despite the rain, we went outside.',exampleUa:'Попри дощ, ми вийшли на вулицю.'},
{id:15,word:'maintain',translation:'підтримувати',pronunciation:'/meɪnˈteɪn/',category:'Verb',level:'B2',explanation:'to keep something at the same level or condition',example:'It is important to maintain focus.',exampleUa:'Важливо підтримувати концентрацію.'},
{id:16,word:'aware',translation:'обізнаний / усвідомлювати',pronunciation:'/əˈwer/',category:'Adjective',level:'B2',explanation:'knowing or realizing something',example:'Are you aware of the risks?',exampleUa:'Ти усвідомлюєш ризики?'},
{id:17,word:'approach',translation:'підхід',pronunciation:'/əˈproʊtʃ/',category:'Noun/Verb',level:'B2',explanation:'a way of dealing with something',example:'We need a different approach.',exampleUa:'Нам потрібен інший підхід.'},
{id:18,word:'increase',translation:'збільшувати / збільшення',pronunciation:'/ɪnˈkriːs/',category:'Noun/Verb',level:'B1',explanation:'to become or make greater',example:'We need to increase productivity.',exampleUa:'Нам потрібно підвищити продуктивність.'},
{id:19,word:'rather',translation:'радше / досить',pronunciation:'/ˈræðər/',category:'Adverb',level:'B2',explanation:'preferably or to some degree',example:'I would rather stay home.',exampleUa:'Я б радше залишився вдома.'},
{id:20,word:'challenge',translation:'виклик / складність',pronunciation:'/ˈtʃælɪndʒ/',category:'Noun/Verb',level:'B1',explanation:'a difficult task that tests ability',example:'Learning a language is a challenge.',exampleUa:'Вивчення мови — це виклик.'},
{id:21,word:'concern',translation:'занепокоєння / стосуватися',pronunciation:'/kənˈsɜːrn/',category:'Noun/Verb',level:'B2',explanation:'a worry or something important to someone',example:'Safety is our main concern.',exampleUa:'Безпека — наша головна турбота.'},
{id:22,word:'essential',translation:'необхідний',pronunciation:'/ɪˈsenʃəl/',category:'Adjective',level:'B2',explanation:'completely necessary',example:'Sleep is essential for health.',exampleUa:'Сон необхідний для здоров’я.'},
{id:23,word:'figure out',translation:'розібратися / зрозуміти',pronunciation:'/ˈfɪɡjər aʊt/',category:'Phrasal verb',level:'B2',explanation:'to understand or solve something',example:'I need to figure out how it works.',exampleUa:'Мені потрібно розібратися, як це працює.'},
{id:24,word:'relevant',translation:'релевантний / доречний',pronunciation:'/ˈreləvənt/',category:'Adjective',level:'B2',explanation:'directly connected with the topic',example:'Please include relevant details.',exampleUa:'Додай, будь ласка, доречні деталі.'},
{id:25,word:'consistent',translation:'послідовний / стабільний',pronunciation:'/kənˈsɪstənt/',category:'Adjective',level:'B2',explanation:'doing something in the same reliable way',example:'Consistent practice is the key to progress.',exampleUa:'Регулярна практика — ключ до прогресу.'}
];
export const rules = [
{id:1,title:'Present Perfect',category:'Tense',explanation:'have/has + past participle for past actions connected to the present.',example:'I have finished my homework.'},
{id:2,title:'Present Perfect vs Past Simple',category:'Tenses',explanation:'Use Past Simple for finished past time; Present Perfect when the exact time is not important or the result connects to now.',example:'I went there yesterday. / I have been there before.'},
{id:3,title:'Conditionals',category:'Grammar',explanation:'Use if-clauses to talk about real, possible, or hypothetical situations.',example:'If I have time, I will call you.'},
{id:4,title:'Modal verbs',category:'Grammar',explanation:'can, could, should, must, might and others express ability, advice, obligation or possibility.',example:'You should practice every day.'},
{id:5,title:'Articles',category:'Grammar',explanation:'Use a/an for a non-specific singular noun and the for something specific.',example:'I saw a dog. The dog was friendly.'}
];
