import crypto from 'crypto';
import { generateRegistrationOptions, verifyRegistrationResponse, generateAuthenticationOptions, verifyAuthenticationResponse } from '@simplewebauthn/server';
import {sqlClient,json,parseBody,setCookie,clearAdminCookie,cookie,requireUser,getIp,requireAdmin} from '../db.js';
const MAX_FAILS=6, STEP=30;
function token(){return crypto.randomBytes(32).toString('hex')}
function validSecret(password){const expected=process.env.ADMIN_PASSWORD||'';const a=Buffer.from(String(password||'')),b=Buffer.from(expected);return !!expected&&a.length===b.length&&crypto.timingSafeEqual(a,b)}
function base32(buf){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits=0,val=0,out='';for(const byte of buf){val=(val<<8)|byte;bits+=8;while(bits>=5){bits-=5;out+=alphabet[(val>>bits)&31]}}if(bits)out+=alphabet[(val<<(5-bits))&31];return out}
function secretKey(){const raw=process.env.ADMIN_SECRET||process.env.ADMIN_PASSWORD||'';return crypto.createHash('sha256').update(raw).digest()}
function encryptSecret(secret){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',secretKey(),iv);const enc=Buffer.concat([c.update(secret,'utf8'),c.final()]);return `${iv.toString('base64url')}.${c.getAuthTag().toString('base64url')}.${enc.toString('base64url')}`}
function decryptSecret(stored){const [iv,tag,data]=String(stored||'').split('.');if(!iv||!tag||!data)throw new Error('bad secret');const d=crypto.createDecipheriv('aes-256-gcm',secretKey(),Buffer.from(iv,'base64url'));d.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([d.update(Buffer.from(data,'base64url')),d.final()]).toString('utf8')}
function decodeBase32(secret){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits=0,val=0,out=[];for(const ch of String(secret).replace(/=+$/,'').toUpperCase()){const i=alphabet.indexOf(ch);if(i<0)continue;val=(val<<5)|i;bits+=5;if(bits>=8){bits-=8;out.push((val>>bits)&255)}}return Buffer.from(out)}
function hotp(secret,counter){const b=Buffer.alloc(8);b.writeBigUInt64BE(BigInt(counter));const h=crypto.createHmac('sha1',decodeBase32(secret)).update(b).digest();const off=h[h.length-1]&15;const code=((h[off]&127)<<24)|(h[off+1]<<16)|(h[off+2]<<8)|h[off+3];return String(code%1000000).padStart(6,'0')}
function totp(secret, step=Math.floor(Date.now()/1000/STEP)){return hotp(secret,step)}
function verifyTotp(secret,code){const c=String(code||'').replace(/\s/g,'');if(!/^\d{6}$/.test(c))return false;const now=Math.floor(Date.now()/1000/STEP);for(let d=-1;d<=1;d++)if(totp(secret,now+d)===c)return now+d;return false}
function secretUri(secret,nick){return `otpauth://totp/English%20Flow:${encodeURIComponent(nick)}?secret=${secret}&issuer=English%20Flow&algorithm=SHA1&digits=6&period=${STEP}`}
async function adminExists(sql){const r=await sql`SELECT 1 FROM users WHERE role IN ('admin','moderator') AND status='active' LIMIT 1`;return !!r[0]}
async function createSession(sql,user,req,res,method='password'){const t=token(),ip=getIp(req);await sql`DELETE FROM admin_sessions WHERE expires_at<now() OR user_id=${user.id}`;await sql`INSERT INTO admin_sessions(user_id,token_hash,expires_at,auth_method,last_ip_hash) VALUES(${user.id},encode(digest(${t},'sha256'),'hex'),now()+interval '4 hours',${method},encode(digest(${ip},'sha256'),'hex'))`;setCookie(res,'__Host-ef_admin',t,60*60*4);return {ok:true,exp:Date.now()+4*3600*1000,admin:{id:user.id,nick:user.nick,name:user.name,role:user.role}}}
function webauthnConfig(){const rpID=String(process.env.WEBAUTHN_RP_ID||'').trim(),origin=String(process.env.WEBAUTHN_ORIGIN||'').trim();if(!rpID||!origin)throw new Error('WEBAUTHN_RP_ID та WEBAUTHN_ORIGIN не налаштовані');return{rpID,origin}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');try{const sql=sqlClient();
if(req.method==='GET'){const t=cookie(req,'__Host-ef_admin');if(!t)return json(res,200,{ok:false});const rows=await sql`SELECT u.id,u.nick,u.name,u.role,a.auth_method,a.expires_at,(SELECT enabled FROM admin_2fa WHERE user_id=u.id) AS two_factor FROM admin_sessions a JOIN users u ON u.id=a.user_id WHERE a.token_hash=encode(digest(${t},'sha256'),'hex') AND a.expires_at>now() AND u.role IN ('admin','moderator') AND u.status='active' LIMIT 1`;if(!rows[0]){clearAdminCookie(res);return json(res,200,{ok:false});}await sql`UPDATE admin_sessions SET last_seen_at=now() WHERE token_hash=encode(digest(${t},'sha256'),'hex')`;return json(res,200,{ok:true,admin:rows[0]})}
if(req.method==='DELETE'){const t=cookie(req,'__Host-ef_admin');if(t)await sql`DELETE FROM admin_sessions WHERE token_hash=encode(digest(${t},'sha256'),'hex')`;clearAdminCookie(res);return json(res,200,{ok:true})}
if(req.method==='POST'){
 const body=parseBody(req),action=String(body.action||'login');
 if(action==='passkey-register-options'){
   const admin=await requireAdmin(req,res);if(!admin)return json(res,401,{ok:false,error:'Unauthorized'});const {rpID}=webauthnConfig();const creds=await sql`SELECT credential_id,transports FROM admin_passkeys WHERE user_id=${admin.id}`;const options=await generateRegistrationOptions({rpName:'English Flow Admin',rpID,userID:Buffer.from(admin.id),userName:admin.nick,userDisplayName:admin.name||admin.nick,attestationType:'none',excludeCredentials:creds.map(c=>({id:c.credential_id,transports:c.transports||[]})),authenticatorSelection:{residentKey:'preferred',userVerification:'preferred'}});await sql`INSERT INTO admin_webauthn_challenges(user_id,challenge,kind,expires_at) VALUES(${admin.id},${options.challenge},'registration',now()+interval '5 minutes') ON CONFLICT(user_id) DO UPDATE SET challenge=excluded.challenge,kind='registration',expires_at=excluded.expires_at`;return json(res,200,{ok:true,options})
 }
 if(action==='passkey-register-verify'){
   const admin=await requireAdmin(req,res);if(!admin)return json(res,401,{ok:false,error:'Unauthorized'});const {rpID,origin}=webauthnConfig();const challenge=(await sql`SELECT challenge FROM admin_webauthn_challenges WHERE user_id=${admin.id} AND kind='registration' AND expires_at>now()`)[0];if(!challenge)return json(res,400,{ok:false,error:'Registration challenge expired'});const v=await verifyRegistrationResponse({response:body.response,expectedChallenge:challenge.challenge,expectedOrigin:origin,expectedRPID:rpID});if(!v.verified||!v.registrationInfo)return json(res,400,{ok:false,error:'Passkey verification failed'});const info=v.registrationInfo;const cred=info.credential;await sql`INSERT INTO admin_passkeys(user_id,credential_id,public_key,counter,transports,device_type,backed_up) VALUES(${admin.id},${cred.id},${Buffer.from(cred.publicKey)},${cred.counter},${cred.transports||[]},${info.credentialDeviceType||null},${!!info.credentialBackedUp}) ON CONFLICT(credential_id) DO NOTHING`;await sql`DELETE FROM admin_webauthn_challenges WHERE user_id=${admin.id}`;await sql`INSERT INTO admin_audit_logs(admin_user_id,action,metadata) VALUES(${admin.id},'admin.passkey_registered','{}'::jsonb)`;return json(res,200,{ok:true})
 }
 if(action==='passkey-auth-options'){
   const user=await requireUser(req,res);if(!user)return json(res,401,{ok:false,error:'Спочатку увійди у свій акаунт'});if(!['admin','moderator'].includes(user.role))return json(res,403,{ok:false,error:'Недостатньо прав'});const {rpID}=webauthnConfig();const creds=await sql`SELECT credential_id,transports FROM admin_passkeys WHERE user_id=${user.id}`;if(!creds.length)return json(res,404,{ok:false,error:'Для цього admin-акаунта ще немає passkey'});const options=await generateAuthenticationOptions({rpID,allowCredentials:creds.map(c=>({id:c.credential_id,transports:c.transports||[]})),userVerification:'preferred'});await sql`INSERT INTO admin_webauthn_challenges(user_id,challenge,kind,expires_at) VALUES(${user.id},${options.challenge},'authentication',now()+interval '5 minutes') ON CONFLICT(user_id) DO UPDATE SET challenge=excluded.challenge,kind='authentication',expires_at=excluded.expires_at`;return json(res,200,{ok:true,options})
 }
 if(action==='passkey-auth-verify'){
   const user=await requireUser(req,res);if(!user)return json(res,401,{ok:false,error:'Спочатку увійди у свій акаунт'});if(!['admin','moderator'].includes(user.role))return json(res,403,{ok:false,error:'Недостатньо прав'});const {rpID,origin}=webauthnConfig();const ch=(await sql`SELECT challenge FROM admin_webauthn_challenges WHERE user_id=${user.id} AND kind='authentication' AND expires_at>now()`)[0];if(!ch)return json(res,400,{ok:false,error:'Authentication challenge expired'});const credentialId=String(body.response?.id||'');const stored=(await sql`SELECT * FROM admin_passkeys WHERE user_id=${user.id} AND credential_id=${credentialId} LIMIT 1`)[0];if(!stored)return json(res,403,{ok:false,error:'Невідомий passkey'});const v=await verifyAuthenticationResponse({response:body.response,expectedChallenge:ch.challenge,expectedOrigin:origin,expectedRPID:rpID,credential:{id:stored.credential_id,publicKey:new Uint8Array(stored.public_key),counter:Number(stored.counter),transports:stored.transports||[]}});if(!v.verified)return json(res,401,{ok:false,error:'Passkey verification failed'});await sql`UPDATE admin_passkeys SET counter=${v.authenticationInfo.newCounter},last_used_at=now() WHERE id=${stored.id}`;await sql`DELETE FROM admin_webauthn_challenges WHERE user_id=${user.id}`;return json(res,200,await createSession(sql,user,req,res,'passkey'))
 }
 if(action==='2fa-setup'){const admin=await requireAdmin(req,res);if(!admin)return json(res,401,{ok:false,error:'Unauthorized'});if(!process.env.ADMIN_SECRET&&!process.env.ADMIN_PASSWORD)return json(res,500,{ok:false,error:'ADMIN_SECRET не налаштований'});const exists=(await sql`SELECT enabled FROM admin_2fa WHERE user_id=${admin.id}`)[0];if(exists?.enabled)return json(res,409,{ok:false,error:'2FA вже увімкнено'});const secret=base32(crypto.randomBytes(20));await sql`INSERT INTO admin_2fa(user_id,secret_enc,enabled) VALUES(${admin.id},${encryptSecret(secret)},false) ON CONFLICT(user_id) DO UPDATE SET secret_enc=excluded.secret_enc,enabled=false,created_at=now(),enabled_at=NULL`;return json(res,200,{ok:true,secret,uri:secretUri(secret,admin.nick)})}
 if(action==='2fa-enable'){const admin=await requireAdmin(req,res);if(!admin)return json(res,401,{ok:false,error:'Unauthorized'});const row=(await sql`SELECT secret_enc FROM admin_2fa WHERE user_id=${admin.id} LIMIT 1`)[0];if(!row)return json(res,400,{ok:false,error:'Спочатку створіть 2FA secret'});const secret=decryptSecret(row.secret_enc),step=verifyTotp(secret,body.code);if(step===false)return json(res,400,{ok:false,error:'Невірний 2FA код'});await sql`UPDATE admin_2fa SET enabled=true,enabled_at=now(),last_used_step=${step} WHERE user_id=${admin.id}`;await sql`INSERT INTO admin_audit_logs(admin_user_id,action,metadata) VALUES(${admin.id},'admin.2fa_enabled','{}'::jsonb)`;return json(res,200,{ok:true})}
 if(action==='2fa-disable'){const admin=await requireAdmin(req,res);if(!admin)return json(res,401,{ok:false,error:'Unauthorized'});const row=(await sql`SELECT secret_enc FROM admin_2fa WHERE user_id=${admin.id} AND enabled=true LIMIT 1`)[0];if(!row)return json(res,400,{ok:false,error:'2FA не увімкнено'});const secret=decryptSecret(row.secret_enc);if(!validSecret(body.password)||verifyTotp(secret,body.code)===false)return json(res,400,{ok:false,error:'Потрібен правильний пароль і 2FA код'});await sql`DELETE FROM admin_2fa WHERE user_id=${admin.id}`;await sql`INSERT INTO admin_audit_logs(admin_user_id,action,metadata) VALUES(${admin.id},'admin.2fa_disabled','{}'::jsonb)`;return json(res,200,{ok:true})}
 if(action!=='login')return json(res,400,{ok:false,error:'Unknown admin action'});
 const user=await requireUser(req,res);if(!user)return json(res,401,{ok:false,error:'Спочатку увійди у свій акаунт'});
 const bodyPassword=String(body.password||'').slice(0,256),ip=getIp(req);const fails=(await sql`SELECT count(*)::int n FROM login_attempts WHERE nick_key='__admin_ip__' AND ip_hash=encode(digest(${ip},'sha256'),'hex') AND success=false AND created_at>now()-interval '15 minutes'`)[0];if(Number(fails?.n||0)>=MAX_FAILS)return json(res,429,{ok:false,error:'Забагато невдалих admin-спроб. Спробуй пізніше.'});
 if(!validSecret(bodyPassword)){await sql`INSERT INTO login_attempts(nick_key,ip_hash,success) VALUES('__admin__',encode(digest(${ip},'sha256'),'hex'),false),('__admin_ip__',encode(digest(${ip},'sha256'),'hex'),false)`;return json(res,401,{ok:false,error:'Невірний admin-пароль'});}
 const hasAdmin=await adminExists(sql);
 if(!hasAdmin&&user.status==='active'){await sql`UPDATE users SET role='admin',updated_at=now() WHERE id=${user.id}`;user.role='admin';await sql`INSERT INTO admin_audit_logs(admin_user_id,action,metadata) VALUES(${user.id},'admin.bootstrap','{"method":"ADMIN_PASSWORD"}'::jsonb)`}
 if(!['admin','moderator'].includes(user.role))return json(res,403,{ok:false,error:'Твій акаунт не має admin/moderator ролі'});
 const two=(await sql`SELECT enabled,secret_enc,last_used_step FROM admin_2fa WHERE user_id=${user.id} LIMIT 1`)[0];
 if(two?.enabled){const step=verifyTotp(decryptSecret(two.secret_enc),body.code);if(step===false||String(two.last_used_step||'')===String(step))return json(res,401,{ok:false,error:'Потрібен новий 2FA код',code:'2FA_REQUIRED'});await sql`UPDATE admin_2fa SET last_used_step=${step} WHERE user_id=${user.id}`;return json(res,200,await createSession(sql,user,req,res,'password+totp'))}
 await sql`INSERT INTO login_attempts(nick_key,ip_hash,success) VALUES('__admin__',encode(digest(${ip},'sha256'),'hex'),true),('__admin_ip__',encode(digest(${ip},'sha256'),'hex'),true)`;return json(res,200,await createSession(sql,user,req,res,'password'));
 }
 return json(res,405,{ok:false});
}catch(e){console.error('admin auth',e);return json(res,500,{ok:false,error:'Admin authentication failed'})}}
