import crypto from 'crypto';
import {sqlClient,json,parseBody,setSessionCookie,clearSessionCookie,cookie,publicUser,getIp} from '../db.js';
const SESSION_DAYS=30, WINDOW_MS=15*60*1000, MAX_FAILS=8;
function validNick(n){return /^[A-Za-z0-9_.-]{2,24}$/.test(n)}
function hashPassword(password,salt){return crypto.scryptSync(String(password),salt,64,{N:32768,r:8,p:1,maxmem:64*1024*1024}).toString('hex')}
function verifyPassword(password,stored){const raw=String(stored||'');if(raw.startsWith('s2$')){const [,salt,hash]=raw.split('$');if(!salt||!hash)return false;const got=hashPassword(password,salt);return got.length===hash.length&&crypto.timingSafeEqual(Buffer.from(got),Buffer.from(hash))}const [salt,hash]=raw.split(':');if(!salt||!hash)return false;const got=crypto.scryptSync(String(password),salt,64).toString('hex');return got.length===hash.length&&crypto.timingSafeEqual(Buffer.from(got),Buffer.from(hash))}
function passwordRecord(password){const salt=crypto.randomBytes(16).toString('hex');return `s2$${salt}$${hashPassword(password,salt)}`}
const DUMMY_SALT='english-flow-dummy-salt-rotate-me';
const DUMMY_HASH=hashPassword('dummy-password',DUMMY_SALT);
function token(){return crypto.randomBytes(32).toString('hex')}
async function rateLimited(sql,nick,ip){const [r,i]=await Promise.all([sql`SELECT count(*)::int AS n FROM login_attempts WHERE nick_key=lower(${nick}) AND success=false AND created_at>now()-interval '15 minutes'`,sql`SELECT count(*)::int AS n FROM login_attempts WHERE ip_hash=encode(digest(${ip},'sha256'),'hex') AND success=false AND created_at>now()-interval '15 minutes'`,sql`DELETE FROM login_attempts WHERE created_at<now()-interval '2 days'`]);return Number(r[0]?.n||0)>=MAX_FAILS||Number(i[0]?.n||0)>=20}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method==='OPTIONS')return json(res,200,{ok:true});try{const sql=sqlClient(),body=parseBody(req),action=body.action||'me',nick=String(body.nick||'').trim(),password=String(body.password||''),ip=getIp(req);if(action==='me'){const t=cookie(req,'__Host-ef_session');if(!t)return json(res,200,{ok:true,user:null});const rows=await sql`SELECT u.id,u.nick,u.name,u.role,u.status FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=encode(digest(${t},'sha256'),'hex') AND s.expires_at>now() LIMIT 1`;return json(res,200,{ok:true,user:publicUser(rows[0])})}if(action==='logout'){const t=cookie(req,'__Host-ef_session');if(t)await sql`DELETE FROM sessions WHERE token_hash=encode(digest(${t},'sha256'),'hex')`;clearSessionCookie(res);return json(res,200,{ok:true})}if(action==='check'){if(!validNick(nick))return json(res,200,{ok:true,taken:false});const rows=await sql`SELECT 1 FROM users WHERE lower(nick)=lower(${nick}) AND status<>'deleted' LIMIT 1`;return json(res,200,{ok:true,taken:!!rows[0]})}if(action!=='register'&&action!=='login')return json(res,400,{ok:false,error:'Unknown action'});if(!validNick(nick))return json(res,400,{ok:false,error:'Нік: 2–24 символи, тільки латиниця, цифри, _, ., -'});if(password.length<12)return json(res,400,{ok:false,error:'Пароль мінімум 12 символів'});if(!/[a-z]/.test(password)||!/[A-Z]/.test(password)||!/[0-9]/.test(password))return json(res,400,{ok:false,error:'Пароль має містити великі/малі літери та цифру'});if(await rateLimited(sql,nick,ip))return json(res,429,{ok:false,error:'Забагато невдалих спроб. Спробуй через 15 хвилин.'});if(action==='register'){const name=String(body.name||nick).trim().slice(0,80)||nick;try{const rows=await sql`INSERT INTO users(nick,name,password_hash) VALUES(${nick},${name},${passwordRecord(password)}) RETURNING id,nick,name,role`;const t=token();await sql`INSERT INTO sessions(user_id,token_hash,expires_at) VALUES(${rows[0].id},encode(digest(${t},'sha256'),'hex'),now()+interval '30 days')`;await sql`INSERT INTO login_attempts(nick_key,ip_hash,success) VALUES(lower(${nick}),encode(digest(${ip},'sha256'),'hex'),true)`;setSessionCookie(res,t);return json(res,201,{ok:true,user:publicUser(rows[0])})}catch(e){if(String(e.message).toLowerCase().includes('unique'))return json(res,409,{ok:false,error:'Такий нік уже зайнятий'});throw e}}
const rows=await sql`SELECT id,nick,name,role,password_hash,status,banned_until FROM users WHERE lower(nick)=lower(${nick}) LIMIT 1`;const u=rows[0];const passwordOk=verifyPassword(password,u?.password_hash||`s2$${DUMMY_SALT}$${DUMMY_HASH}`);const valid=u&&u.status==='active'&&(!u.banned_until||new Date(u.banned_until)<=new Date())&&passwordOk;await sql`INSERT INTO login_attempts(nick_key,ip_hash,success) VALUES(lower(${nick}),encode(digest(${ip},'sha256'),'hex'),${!!valid})`;if(!valid)return json(res,401,{ok:false,error:'Невірний нік або пароль'});if(String(u.password_hash||'').startsWith('s2$')===false) await sql`UPDATE users SET password_hash=${passwordRecord(password)} WHERE id=${u.id}`;const t=token();await sql`INSERT INTO sessions(user_id,token_hash,expires_at) VALUES(${u.id},encode(digest(${t},'sha256'),'hex'),now()+interval '30 days')`;await sql`UPDATE users SET last_login_at=now(),updated_at=now() WHERE id=${u.id}`;setSessionCookie(res,t);return json(res,200,{ok:true,user:publicUser(u)})}catch(e){return json(res,500,{ok:false,error:'Authentication failed'})}}
